import React,{useCallback,useEffect,useMemo,useRef,useState}from"react";
import Editor from"@monaco-editor/react";
import ReactMarkdown from"react-markdown";
import remarkGfm from"remark-gfm";
import{Terminal as XTerminal}from"xterm";
import{FitAddon}from"xterm-addon-fit";
import"xterm/css/xterm.css";
import{Activity,AlertCircle,Bot,Check,ChevronDown,ChevronRight,File,FileCode2,FileJson,FileText,Folder,FolderOpen,GitBranch,GitCommit,RefreshCw,Search,Send,Settings,Sparkles,Square,Terminal as TerminalIcon,Trash2,Undo2,X,Save,Play,Plus}from"lucide-react";

const API="http://127.0.0.1:8000",AGENT_WS="ws://127.0.0.1:8000/ws/agent",TERM_WS="ws://127.0.0.1:8000/ws/terminal";
const LANG={py:"python",js:"javascript",jsx:"javascript",ts:"typescript",tsx:"typescript",json:"json",html:"html",css:"css",scss:"scss",md:"markdown",txt:"plaintext",yaml:"yaml",yml:"yaml",xml:"xml",sql:"sql",sh:"shell",bat:"bat",cmd:"bat",ps1:"powershell",cpp:"cpp",c:"c",h:"c",hpp:"cpp",java:"java",rs:"rust",go:"go",php:"php",v:"verilog",sv:"verilog"};
const lang=n=>LANG[n.split(".").pop()?.toLowerCase()]||"plaintext";
const base=p=>p.replace(/[\\/]+$/,"").split(/[\\/]/).pop()||p;
function icon(n,s=15){let e=n.split(".").pop()?.toLowerCase();if(["py","js","jsx","ts","tsx","cpp","c","h","hpp","java","rs","go","php","v","sv"].includes(e))return <FileCode2 size={s}/>;if(["json","yaml","yml","xml"].includes(e))return <FileJson size={s}/>;if(["md","txt"].includes(e))return <FileText size={s}/>;return <File size={s}/>}
function norm(n){if(!n)return null;return{...n,children:(n.children||[]).map(norm).sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==="directory"?-1:1)}}
function Tree({n,l=0,expanded,toggle,open}){let d=n.type==="directory",o=expanded.has(n.path);return <div><button className="tree-row" style={{paddingLeft:10+l*16}} onClick={()=>d?toggle(n.path):open(n)}><span className="tree-arrow">{d?(o?<ChevronDown size={14}/>:<ChevronRight size={14}/>):null}</span><span className="tree-icon">{d?(o?<FolderOpen size={15}/>:<Folder size={15}/>):icon(n.name)}</span><span className="tree-name">{n.name}</span></button>{d&&o&&n.children?.map(c=><Tree key={c.path} n={c} l={l+1} expanded={expanded} toggle={toggle} open={open}/>)}</div>}

export default function App(){
 const[projectPath,setProjectPath]=useState(localStorage.getItem("dr_project_path")||"");
 const[tree,setTree]=useState(null),[expanded,setExpanded]=useState(new Set()),[treeLoading,setTreeLoading]=useState(false),[treeError,setTreeError]=useState("");
 const[files,setFiles]=useState([]),[active,setActive]=useState(null),[msg,setMsg]=useState(""),[events,setEvents]=useState([]);
 const[backend,setBackend]=useState("checking"),[agentRunning,setAgentRunning]=useState(false),[side,setSide]=useState("explorer"),[bottom,setBottom]=useState("terminal");
 const[query,setQuery]=useState(""),[replace,setReplace]=useState(""),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[mdPreview,setMdPreview]=useState(false);
 const[git,setGit]=useState({available:false,is_repo:false,branch:"No Git",changes:[]}),[gitBusy,setGitBusy]=useState(false);
 const agentRef=useRef(),termRef=useRef(),termHost=useRef(),fitRef=useRef(),outRef=useRef();
 const current=useMemo(()=>files.find(f=>f.path===active),[files,active]),name=projectPath?base(projectPath):"";
 const add=useCallback((type,text)=>setEvents(p=>[...p,{id:crypto.randomUUID(),type,text,time:new Date().toLocaleTimeString()}]),[]);
 const health=useCallback(async()=>{try{let r=await fetch(`${API}/api/health`);if(!r.ok)throw 0;setBackend("connected")}catch{setBackend("offline")}},[]);
 useEffect(()=>{health();let t=setInterval(health,5000);return()=>clearInterval(t)},[health]);
 const loadTree=useCallback(async()=>{if(!projectPath){setTree(null);return}setTreeLoading(true);setTreeError("");try{let r=await fetch(`${API}/api/project/tree?path=${encodeURIComponent(projectPath)}`),d=await r.json();if(!r.ok)throw Error(d.detail||"Could not load project");let t=norm(d);setTree(t);setExpanded(new Set([t.path]))}catch(e){setTree(null);setTreeError(e.message);add("error",`Project tree: ${e.message}`)}finally{setTreeLoading(false)}},[projectPath,add]);
 useEffect(()=>{loadTree()},[loadTree]);
 const loadGit=useCallback(async()=>{if(!projectPath)return;try{let r=await fetch(`${API}/api/git/status?path=${encodeURIComponent(projectPath)}`),d=await r.json();if(r.ok)setGit(d)}catch{}},[projectPath]);
 useEffect(()=>{loadGit()},[loadGit]);
 const choose=async()=>{try{let r=await fetch(`${API}/api/project/pick-folder`,{method:"POST"}),d=await r.json();if(!r.ok)throw Error(d.detail||"Folder picker failed");if(!d.selected||!d.path)return;setProjectPath(d.path);localStorage.setItem("dr_project_path",d.path);setFiles([]);setActive(null);setEvents([]);add("system",`Project opened: ${d.path}`)}catch(e){add("error",`Open Folder: ${e.message}`)}};
 const toggle=p=>setExpanded(s=>{let n=new Set(s);n.has(p)?n.delete(p):n.add(p);return n});
 const open=async f=>{try{let r=await fetch(`${API}/api/project/file?path=${encodeURIComponent(f.path)}`),d=await r.json();if(!r.ok)throw Error(d.detail||"Could not open file");setFiles(p=>p.some(x=>x.path===f.path)?p.map(x=>x.path===f.path?{...x,content:d.content}:x):[...p,{path:f.path,name:f.name,content:d.content,language:lang(f.name)}]);setActive(f.path);setMdPreview(false)}catch(e){add("error",`Open ${f.name}: ${e.message}`)}};
 const save=async()=>{if(!current)return;try{let r=await fetch(`${API}/api/project/file`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:current.path,content:current.content})}),d=await r.json();if(!r.ok)throw Error(d.detail||"Could not save");setFiles(p=>p.map(x=>x.path===active?{...x,savedAt:Date.now()}:x));add("system",`Saved ${current.path}`);loadGit()}catch(e){add("error",`Save: ${e.message}`)}};
 const update=v=>setFiles(p=>p.map(x=>x.path===active?{...x,content:v||""}:x));
 const close=p=>{let i=files.findIndex(x=>x.path===p),n=files.filter(x=>x.path!==p);setFiles(n);if(active===p)setActive(n[Math.max(0,i-1)]?.path||null)};
 const run=async()=>{if(!current)return;setBottom("output");try{let r=await fetch(`${API}/api/project/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:current.path})}),d=await r.json();if(d.output)add("output",d.output);if(d.stderr)add("error",d.stderr);if(d.needs_terminal){setBottom("terminal");add("system","This file requires the integrated Terminal.")}else add(d.exit_code===0?"system":"error",`Run finished with exit code ${d.exit_code}`)}catch(e){add("error",`Run: ${e.message}`)}};
 const search=async()=>{if(!projectPath||!query.trim()){setResults([]);return}setSearching(true);try{let r=await fetch(`${API}/api/search?path=${encodeURIComponent(projectPath)}&query=${encodeURIComponent(query)}`),d=await r.json();if(!r.ok)throw Error(d.detail||"Search failed");setResults(d.items||[])}catch(e){add("error",`Search: ${e.message}`)}finally{setSearching(false)}};
 const replaceAll=async()=>{if(!projectPath||!query)return;let fs=[...new Set(results.map(x=>x.relative_path).filter(Boolean))];if(!confirm(`Replace "${query}" with "${replace}" in ${fs.length} matching file(s)?`))return;try{let r=await fetch(`${API}/api/search/replace`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:projectPath,query,replacement:replace,files:fs.length?fs:undefined,case_sensitive:true})}),d=await r.json();if(!r.ok)throw Error(d.detail||"Replace failed");add("system",`Replaced ${d.total_replacements} occurrence(s) in ${d.files_changed} file(s).`);loadTree();loadGit()}catch(e){add("error",`Replace: ${e.message}`)}};
 const send=()=>{let text=msg.trim();if(!text||agentRunning)return;if(!projectPath){add("error","Open a project first.");return}setAgentRunning(true);setBottom("output");add("user",text);let ws=new WebSocket(AGENT_WS);agentRef.current=ws;ws.onopen=()=>{ws.send(JSON.stringify({message:text,project_path:projectPath}));setMsg("")};ws.onmessage=e=>{try{let d=JSON.parse(e.data);if(d.type==="start")add("system",d.message||"DevResearcher started.");else if(d.type==="output")add("agent",d.text||"");else if(d.type==="error")add("error",d.message||"Agent error.");else if(d.type==="done"){add(d.exit_code===0?"system":"error",`DevResearcher finished (exit ${d.exit_code}).`);setAgentRunning(false);ws.close()}}catch{add("agent",e.data)}};ws.onerror=()=>{setBackend("offline");setAgentRunning(false);add("error","Agent WebSocket error. Check FastAPI on port 8000.")};ws.onclose=()=>{agentRef.current=null;setAgentRunning(false)}};
 const stop=()=>{try{agentRef.current?.close()}catch{}agentRef.current=null;setAgentRunning(false);add("system","Agent stopped.")};
 const initTerm=useCallback(()=>{if(!termHost.current||termRef.current||!projectPath)return;let t=new XTerminal({cursorBlink:true,fontSize:13,convertEol:true,theme:{background:"#0b0f14",foreground:"#d8dee9",cursor:"#7dd3fc"}}),fit=new FitAddon();t.loadAddon(fit);t.open(termHost.current);fit.fit();termRef.current=t;fitRef.current=fit;t.writeln("DevResearcher integrated terminal");t.writeln(`Workspace: ${projectPath}`);let ws=new WebSocket(TERM_WS);termRef.current.ws=ws;ws.onopen=()=>ws.send(JSON.stringify({type:"init",cwd:projectPath,shell:"cmd"}));ws.onmessage=e=>{try{let d=JSON.parse(e.data);if(d.type==="ready")t.writeln(`[Shell ready: ${d.shell}]`);else if(d.type==="data")t.write(d.data);else if(d.type==="exit")t.writeln(`\\r\\n[Shell exited: ${d.code}]`);else if(d.type==="error")t.writeln(`\\r\\n[Terminal error] ${d.data}`)}catch{}};t.onData(x=>{if(ws.readyState===1)ws.send(JSON.stringify({type:"input",data:x}))})},[projectPath]);
 useEffect(()=>{if(bottom==="terminal")setTimeout(initTerm,0)},[bottom,initTerm]);
 useEffect(()=>()=>{try{agentRef.current?.close();termRef.current?.ws?.close();termRef.current?.dispose()}catch{}},[]);
 const restartTerm=()=>{try{termRef.current?.ws?.close();termRef.current?.dispose()}catch{}termRef.current=null;setBottom("output");setTimeout(()=>setBottom("terminal"),40)};
 const gitAction=async(action,extra={})=>{if(!projectPath)return;setGitBusy(true);try{let r=await fetch(`${API}/api/git/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:projectPath,...extra})}),d=await r.json();if(!r.ok)throw Error(d.detail||d.error||"Git failed");add(d.success===false?"error":"system",d.output||`${action} completed`);loadGit()}catch(e){add("error",`Git ${action}: ${e.message}`)}finally{setGitBusy(false)}};
 useEffect(()=>{outRef.current?.scrollTo({top:outRef.current.scrollHeight})},[events]);
 const onKey=e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey)){e.preventDefault();send()}};
 return <div className="app">
  <header className="top"><div className="brand"><span className="mark"><Sparkles size={16}/></span><b>DevResearcher</b><small>AI Engineering Workspace</small></div><div className="topright"><button className="openbtn" onClick={choose}><FolderOpen size={15}/>Open Folder</button><button className="iconbtn" onClick={()=>{loadTree();loadGit()}}><RefreshCw size={15}/></button><span className={`health ${backend}`}>{backend==="connected"?<><i/>Backend connected</>:backend==="checking"?"Checking…":"Backend offline"}</span></div></header>
  <div className="body"><nav className="activity"><button className={side==="explorer"?"on":""} onClick={()=>setSide("explorer")}><FolderOpen/></button><button className={side==="search"?"on":""} onClick={()=>setSide("search")}><Search/></button><button className={side==="git"?"on":""} onClick={()=>setSide("git")}><GitCommit/><div/></button><span/><button><Settings/></button></nav>
   <aside className="side">
    {side==="explorer"&&<><div className="head"><span>EXPLORER</span><div><button onClick={choose}><Plus/></button><button onClick={loadTree}><RefreshCw/></button></div></div><div className="workspace"><b><FolderOpen size={14}/>{name||"No folder opened"}</b><small>{projectPath||"Use Open Folder to choose a project."}</small></div><div className="scroll">{treeLoading?<div className="empty"><RefreshCw className="spin"/><span>Loading project…</span></div>:treeError?<div className="error"><AlertCircle/><b>Project could not be loaded</b><small>{treeError}</small><button onClick={loadTree}>Retry</button></div>:tree?<Tree n={tree} expanded={expanded} toggle={toggle} open={open}/>:<div className="empty"><FolderOpen size={26}/><span>Open a project folder</span><button onClick={choose}>Choose Folder</button></div>}</div></>}
    {side==="search"&&<><div className="head"><span>SEARCH</span></div><div className="searchbox"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search in project"/><input value={replace} onChange={e=>setReplace(e.target.value)} placeholder="Replace with"/><div><button onClick={search}>{searching?"Searching…":"Search"}</button><button onClick={replaceAll} disabled={!results.length}>Replace</button></div></div><div className="results">{results.map((r,i)=><button key={i} onClick={()=>open({path:r.path,name:r.name,type:"file"})}><b>{r.name}</b><small>{r.relative_path}{r.line?`:${r.line}`:""}</small>{r.line_text&&<code>{r.line_text}</code>}</button>)}</div></>}
    {side==="git"&&<><div className="head"><span>SOURCE CONTROL</span><button onClick={loadGit}><RefreshCw/></button></div>{!git.is_repo?<div className="empty"><GitCommit size={25}/><span>{git.available?"This project is not a Git repository.":"Git unavailable."}</span></div>:<div className="git"><div className="branch"><GitBranch size={14}/><b>{git.branch}</b><small>{git.changes?.length||0} change(s)</small></div><div className="gbuttons"><button disabled={gitBusy} onClick={()=>gitAction("stage")}><Check/>Stage</button><button disabled={gitBusy} onClick={()=>gitAction("unstage")}><Undo2/>Unstage</button><button disabled={gitBusy} onClick={()=>gitAction("commit",{message:prompt("Commit message:","Update project")||""})}><GitCommit/>Commit</button></div>{git.changes?.map((c,i)=><div className="change" key={i}><b>{c.status}</b><span>{c.path}</span></div>)}</div>}</>}
    <footer>{projectPath?"Workspace active":"No workspace"}</footer>
   </aside>
   <main className="main">
    <div className="tabs">{files.length?files.map(f=><div key={f.path} className={`tab ${active===f.path?"active":""}`} onClick={()=>setActive(f.path)}>{icon(f.name,14)}<span>{f.name}</span>{!f.savedAt&&<i/>}<button onClick={e=>{e.stopPropagation();close(f.path)}}><X/></button></div>):<span className="notab">No file open</span>}<div className="grow"/>{current&&<><button className="tool" onClick={save}><Save/></button><button className="tool" onClick={run}><Play/></button>{current.name.endsWith(".md")&&<button className="tool" onClick={()=>setMdPreview(v=>!v)}><FileText/></button>}</>}</div>
    <section className="editor">{current?(mdPreview?<div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{current.content}</ReactMarkdown></div>:<Editor height="100%" theme="vs-dark" language={current.language} value={current.content} onChange={update} onMount={(editor, monaco)=>editor.addCommand(monaco.KeyMod.CtrlCmd|monaco.KeyCode.KeyS,save)} options={{minimap:{enabled:true},fontSize:14,automaticLayout:true,wordWrap:"off",padding:{top:12},smoothScrolling:true,scrollBeyondLastLine:false}}/>):<div className="welcome"><div className="welmark"><Bot size={40}/></div><h1>DevResearcher</h1><p>AI engineering, coding, debugging & research workspace.</p><div><button onClick={choose}><FolderOpen/>Open Folder</button><button onClick={()=>document.querySelector(".agent-input")?.focus()}><Bot/>Ask DevResearcher</button></div><small>Select any local Windows project. The selected path is sent to the agent as project context.</small></div>}</section>
    <section className="bottom"><div className="panelhead"><div><button className={bottom==="terminal"?"sel":""} onClick={()=>setBottom("terminal")}><TerminalIcon/>TERMINAL</button><button className={bottom==="output"?"sel":""} onClick={()=>setBottom("output")}><Activity/>OUTPUT</button><button className={bottom==="agent"?"sel":""} onClick={()=>setBottom("agent")}><Bot/>DEVRESEARCHER</button></div>{bottom==="terminal"?<button onClick={restartTerm}><RefreshCw/></button>:bottom==="output"?<button onClick={()=>setEvents([])}><Trash2/></button>:null}</div>{bottom==="terminal"&&<div className="terminal"><div ref={termHost}/></div>}{bottom==="output"&&<div className="output" ref={outRef}>{events.length?events.slice(-200).map(e=><article className={e.type} key={e.id}><header><b>{e.type.toUpperCase()}</b><time>{e.time}</time></header><pre>{e.text}</pre></article>):<span>No output yet.</span>}</div>}{bottom==="agent"&&<div className="agentsum"><Bot/><div><b>{agentRunning?"DevResearcher is working…":"DevResearcher is ready."}</b><small>{projectPath||"Open a project to give the agent a workspace."}</small></div></div>}</section>
    <section className="composer"><div className="ctop"><div><Bot/><b>DevResearcher</b><span className={agentRunning?"work":""}>{agentRunning?"Working":"Ready"}</span></div>{agentRunning&&<button onClick={stop}><Square/>Stop</button>}</div><div className="cbody"><textarea className="agent-input" value={msg} disabled={agentRunning} onChange={e=>setMsg(e.target.value)} onKeyDown={onKey} placeholder={projectPath?`Ask DevResearcher about ${name}…`:"Open a project and ask DevResearcher…"}/><button onClick={send} disabled={!msg.trim()||agentRunning||backend !== "connected"}>{agentRunning?<Activity className="spin"/>:<Send/>}</button></div><div className="cfoot"><span><kbd>Ctrl</kbd>+<kbd>Enter</kbd> to send</span><span title={projectPath}>{projectPath||"No project selected"}</span></div></section>
   </main>
  </div>
  <footer className="status"><span><GitBranch/> {git.is_repo?git.branch:"No Git"}</span><span><Activity/> {backend==="connected"?"Backend Connected":"Backend Offline"}</span><span>{name||"No workspace"}</span><span>UTF-8 · Windows · DevResearcher</span></footer>
 </div>
}